// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1M31caz3dtx4DO5QKhW1MN7j8k6cunQU',
    appId: '1:846638036143:web:15c629d494deac6580105a',
    messagingSenderId: '846638036143',
    projectId: 'silent-space-21990',
    authDomain: 'silent-space-21990.firebaseapp.com',
    storageBucket: 'silent-space-21990.firebasestorage.app',
    measurementId: 'G-N4S990QKY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_4jcl6c3acNzKMz-2iN0m2fbL_QFATo',
    appId: '1:846638036143:android:dff0051f473b668c80105a',
    messagingSenderId: '846638036143',
    projectId: 'silent-space-21990',
    storageBucket: 'silent-space-21990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt1JOWC6sqhFzaAu6FW2J9XX2dsSm-rpE',
    appId: '1:846638036143:ios:b3ca63c0930e36cb80105a',
    messagingSenderId: '846638036143',
    projectId: 'silent-space-21990',
    storageBucket: 'silent-space-21990.firebasestorage.app',
    iosBundleId: 'com.example.silentSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt1JOWC6sqhFzaAu6FW2J9XX2dsSm-rpE',
    appId: '1:846638036143:ios:b3ca63c0930e36cb80105a',
    messagingSenderId: '846638036143',
    projectId: 'silent-space-21990',
    storageBucket: 'silent-space-21990.firebasestorage.app',
    iosBundleId: 'com.example.silentSpace',
  );
}
